input: "C:/Users/Regine/Downloads/td-generator-tool/library-project"
output: "C:/Users/Regine/Downloads/td-generator-tool/library-exercise"

# business | any
mode: any

# üî• Mode MANUEL (prioritaire si pr√©sent)
methods:
  - id: "ca.umontreal.library.Library#addBook(Book)"
    cut: full

  - id: "ca.umontreal.library.Library#borrowBook(String)"
    cut: partial
    keepStatements: 1   # optionnel (par d√©faut = 1)

# optionnel : si true, ignore une m√©thode non trouv√©e (sinon erreur)
ignoreMissingMethods: false

# mode RANDOM (utilis√© seulement si methods est vide)
random: 3

# exclusions (utile seulement en mode random)
exclude: []
excludeFile: ""
